### ISSUE TITLE
We need to come up with the general story / point of this game.

### ISSUE THREAD

**Issue by ozyx** [SaddlebackCSS/spring-break-text-adventure#1]
@ainix @TheFirstLairron @AustinJP25 @LordFreyr 

If I missed anybody in the tags, I apologize.

Requirements:
- It must be awesome.
- It must have something to do with spring break.

I'm thinking we can have a game that is basically a big adventure game, with the player going from room to room. Each room can have a description and different directions the player can move by entering a (N, S, E, W) for north, south, east, west. Maybe we can program some keywords in the description so if the player enters certain keywords special events are triggered.

If you have any ideas please comment with them in this thread. :sunglasses: :+1: 

After we figure out the general idea of the game we will need an awesome and funny name for our game.

**Comment by TheFirstLairron** [comment]
Idea: on the beach when you are sucks out to sea, you find yourself pulled into an undersea cave that is a maze and you need to find your way home before spring break is over so you can make it back to school.

**Comment by ozyx** [comment]
idea: You get invited to the coolest party in school at a friend's (Farid) gigantic mansion over spring break. You wander away from the crowd and become lost in the maze of rooms in this gigantic mansion. You objective is to either find your way back to the party or uncover the mansion's deep, dark, scary secrets. Or just break everything in the house.

**Comment by LordFreyr** [comment]
Idea:
   It's spring break, and word on the street is there's going to be a huge party tomorrow night!  The next day you're able to find out it's at some mansion and decide to go!  So you show up and spend the night partying!
  The next day, you wake up and have to find all your missing crap laying around throughout the place before you can leave to go home.

**Comment by TheFirstLairron** [comment]
Idea: At a mansion house party, break as many things as you can without getting caught by the host?

**Comment by ozyx** [comment]
These are all great ideas, I think we should combine them all. Multiple win scenarios, basically an adventure game where many different things can happen depending on where you go and what you do. That way we can implement all of these ideas and make a truly fun / hilarious text game.

**Comment by ghost** [comment]
I like the idea where you stay up the whole night in the mansion (greeted very well by a computerized mansion), and upon waking up you find yourself in a maze. The maze could consist of rooms and hallways, and to get out of the maze part of the mansion, you must enter through a correct sequence of rooms, using clues that you gather while examining the rooms. (also you end up in the maze because the computer wants to keep you as a guest, and gives you everything you want like an automated lunch, a TV, a Pool room, and a Tennis court (all of them indoors), but when it comes to leaving you're kind of trapped, because you don't know which doors to go through to leave).

The Mansion could be controlled by an evil() computerized system that monitors your movement through the rooms and tries to stop you in the end when you escape. The clues that you gather from the previous maze dweller could help you find what to do to disable the computer (like typing a code word into a terminal) without it noticing, thus escaping without the computer being able to stop you.

There can be two endings to the game, one where you just find a way out, and the second where you solve a mystery that happened in that maze with the previous maze dweller and also escape the maze in some awesome fashion.

**Comment by ozyx** [comment]
Closing.
