### ISSUE TITLE
We need room descriptions. Lots of room descriptions.

### ISSUE THREAD

**Issue by ozyx** [SaddlebackCSS/spring-break-text-adventure#7]
This depends on #5 being complete.

**Comment by ainix** [comment]
I was thinking about the the general format in which the room descriptions could be written and I came up with something along the lines of:

"This room seems barely used, you think. Or the occupant must've had very questionable aesthetics and personal hygienic issues, a thought you would rather not entertain at the moment after a big meal. Dust and moldy odors mingle in the air. Not to mention the furnishing that appears at least several times as old as any attendee of this party: a plain-looking bed with generic, white comforters and pillows sitting unassumingly in the corner; a slice of cake on the nightstand with a note on it that reads "eat me;" an antique wooden wardrobe with low, creepy sounds coming from behind the closed doors; and a fancy-looking vase that seems suspiciously out of place in this room.

You can choose to: 
1) Lie on the bed and anguish over your poor life choices.
2) Eat the cake despite your survival instincts warning you not to.
3) Open the doors of the wardrobe because why not, you can't die from being devoured by a large spider or something equally nightmare-ish; this is a game, duh.
4) Check out the vase that is apparently begging for attention.

_If you type: lie on the bed_: the bed collapses, obviously. Your left shoulder is now dislocated. 
_If you type: eat the cake:_ much to your horror (or delight, depends on how much you like fantasies and fairy tales) you feel yourself shrinking; you've become as tiny as Alice in Wonderland!
_If you type: open the doors to the wardrobe:_ you can hear the sounds clearly now; it's the howling wind. This wardrobe leads to Narnia! 
_If you type: check out the vase:_ (I haven't thought of what it could be yet, apologies.)"

So the interactions with the objects in the room (or this whole thing, really) are really just made up on the spot, I don't anything solid in mind yet. I was just brainstorming what the room descriptions could be like in general and see if y'all have any ideas, things you would like to add or change, or if you just think this is utterly bonkers; any constructive criticism welcomed! We don't have to write it like this at all if you think it wouldn't really work with the game. Just a suggestion. But if by any chance you think it can work, I can work off of that as sort of a template.

Aini

**Comment by ozyx** [comment]
Closing.
